### ISSUE TITLE
PLEASE DESCRIBE THE BUG

### ISSUE THREAD

**Issue by selfagency** [ActionsDesk/github-org-repo-metrics-action#6]
### Describe the bug

The action works great if manually triggered, but if run on a schedule, it fails with the following error:

```
TypeError: Cannot read property 'login' of undefined
    at /home/runner/work/_actions/ActionsDesk/github-org-repo-metrics-action/v1.0.0/dist/index.js:20:324835
    at /home/runner/work/_actions/ActionsDesk/github-org-repo-metrics-action/v1.0.0/dist/index.js:20:348215
    at Object.<anonymous> (/home/runner/work/_actions/ActionsDesk/github-org-repo-metrics-action/v1.0.0/dist/index.js:20:348254)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:[32](https://github.com/unstoppabledomains/unstoppable-devops/runs/6133330610?check_suite_focus=true#step:2:32))
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47
##[debug]Node Action run completed with exit code 1
```

### To Reproduce

```
name: Velocity report

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  velocity-report:
    runs-on: ubuntu-latest
    steps:
      - name: Get organization repository metrics
        uses: ActionsDesk/github-org-repo-metrics-action@v1.0.0
        with:
          token: ${{ secrets.ORG_TOKEN }}
          days: 7

```

### Expected behavior

To run just as well under a schedule as it does manually.
